export const JOBS = {
  WAVE: 'order-wave',
  WAVE_TIMEOUT: 'order-wave-timeout',
  PRICE_TIMEOUT: 'order-price-timeout',
  AUTO_CLOSE: 'order-auto-close',
  PRESENCE_SWEEP: 'presence-sweep',
  PLANNED_EXPIRY: 'planned-order-expiry',
  PLANNED_CONFIRM_TIMEOUT: 'planned-order-confirm-timeout',
  PLANNED_AUTO_CLOSE: 'planned-order-auto-close',
  UPLOAD_CLEANUP: 'pending-upload-cleanup',
  UPLOAD_SCAN: 'pending-upload-scan',
  UPLOAD_SCAN_SWEEP: 'pending-upload-scan-sweep',
  MASTER_DOCUMENT_SCAN: 'master-document-scan',
  DISPUTE_EVIDENCE_SCAN: 'dispute-evidence-scan',
  PERSISTENT_FILE_SCAN_SWEEP: 'persistent-file-scan-sweep',
} as const;
